  deploy:
    runs-on: windows-latest
    needs: build

    strategy:
      matrix:
        app-name:
          - cnapp5-01-app-jou7fcojzfbam
          - cnapp5-02-app-k3acalwvqupjq
          - cnapp5-03-app-fbspsu64udrbo
          - cnapp5-04-app-erniiql7yrxle
          - cnapp5-05-app-5x7jd6t24ewas

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_17B9F474DC0F49EEBCE8B7CD3F06263A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F61348EC979A46BEA65E045323C81EBD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_95E6FABB9E25411FB3BBFA639ED8F08A }}

      - name: Deploy to ${{ matrix.app-name }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ matrix.app-name }}
          slot-name: Production
          package: .